program : 
	javac ca/mcgill/ecse420/a3/Node.java ca/mcgill/ecse420/a3/FineGrainedContains.java ca/mcgill/ecse420/a3/ContainsTest.java

run : program
	java ca.mcgill.ecse420.a3.ContainsTest

clean : 
	rm ca/mcgill/ecse420/a3/Node*.class ca/mcgill/ecse420/a3/FineGrainedContains*.class ca/mcgill/ecse420/a3/ContainsTest*.class